### ISSUE TITLE
Accessibility: Improve the look on high contrast mode

### ISSUE THREAD

**Issue by oczki** [tehoko/inspiracje#29]
When a highly contrasting color theme is selected in Windows, **the page loses its visual structure**. Buttons, links, word sections, sliding sheets, and other elements look flat and non-interactive.

The root cause is **relying on color fills and box-shadows to emulate borders and outlines**. A high contrast theme removes all color fills and shadows, and forces its own colors for borders and outlines. Therefore, adding a **transparent** border/outline will not impact the default look while making the high contrast one more accessible.

![Selecting color theme in Windows 11](https://github.com/user-attachments/assets/8eb64b28-72ad-4446-a4cc-0d09f06f3549)

| Default | High contrast |
| --- | --- |
| ![Regular look of Inspiration Depot](https://github.com/user-attachments/assets/c5e71fab-f65e-4d51-a4dd-920ec157a58c) | ![High contrast look of Inspiration Depot](https://github.com/user-attachments/assets/1203a33b-76ef-4caa-abed-7fc3b426f6bf) |

## Subtasks

- [x] Add a transparent outline when an interactive element is focused
- [x] Add borders to word sections
- [x] Add borders to buttons
    - [x] Arrows: maybe no border by default, but on hover? (They have no border on regular contrast mode)
    - [x] Mark the trigger of the currently open sliding sheet
- [x] Add borders to hyperlinks
- [x] Add borders to inputs (checkboxes)
- [x] Add borders to footer and sliding sheets
- [x] Add borders to settings prompt
- [x] Tests: empty state after hiding all categories, sliding all sheets on/off, advancing all words, look in compact mode

**Comment by oczki** [comment]
Huge improvements all around. I've learned so much while working on this. Even if nobody will see these improvements (most people use it on mobile, not on Windows high contrast mode), I'm still very satisfied with the results.

| Before | After |
| --- | --- |
| ![High contrast look before changes](https://github.com/user-attachments/assets/1203a33b-76ef-4caa-abed-7fc3b426f6bf) | ![High contrast look after changes](https://github.com/user-attachments/assets/9c5146a0-c3dd-41ac-a729-50c7925690de) |

**Comment by oczki** [comment]
Video comparison with interactions. Left: old, right: new.

https://github.com/user-attachments/assets/43bb6683-70d3-4be9-9154-aac3f968075d
